const API='/api';
function getToken(){return localStorage.getItem('wavebox-token')}
function setToken(t){if(t)localStorage.setItem('wavebox-token',t);else localStorage.removeItem('wavebox-token')}
function headers(x={}){const h={...x};const t=getToken();if(t)h.Authorization=`Bearer ${t}`;return h}
async function req(path,opts={}){const r=await fetch(`${API}${path}`,{...opts,headers:headers(opts.headers||{})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Fehler');return d}
export const api={
  async login(e,p){const d=await req('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})});setToken(d.token);return d.user},
  async register(n,e,p){const d=await req('/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:n,email:e,password:p})});setToken(d.token);return d.user},
  async logout(){try{await req('/auth/logout',{method:'POST'})}catch{}setToken(null)},
  async me(){if(!getToken())return null;try{return(await req('/auth/me')).user}catch{setToken(null);return null}},
  async getTracks(){return req('/tracks')},
  async uploadTrack(audioFile,coverFile,meta){const f=new FormData();if(audioFile)f.append('file',audioFile);if(coverFile)f.append('cover',coverFile);Object.entries(meta).forEach(([k,v])=>f.append(k,String(v)));const t=getToken();const r=await fetch(`${API}/tracks`,{method:'POST',headers:t?{Authorization:`Bearer ${t}`}:{},body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);return d},
  async updateTrack(id,data){return req(`/tracks/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})},
  async updateCover(id,file){const f=new FormData();f.append('cover',file);const t=getToken();const r=await fetch(`${API}/tracks/${id}/cover`,{method:'PUT',headers:t?{Authorization:`Bearer ${t}`}:{},body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);return d},
  async deleteTrack(id){return req(`/tracks/${id}`,{method:'DELETE'})},
  async saveLyrics(id,lyrics){return req(`/tracks/${id}/lyrics`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({lyrics})})},
  async deleteLyrics(id){return req(`/tracks/${id}/lyrics`,{method:'DELETE'})},
  async generateLyrics(id){return req(`/tracks/${id}/generate-lyrics`,{method:'POST'})},
  async getLikes(){return req('/likes')},
  async toggleLike(tid){return req(`/likes/${tid}`,{method:'POST'})},
  async trackPlay(tid){return req(`/tracks/${tid}/play`,{method:'POST'}).catch(()=>{})},
  async getPlayCounts(){return req('/play-counts').catch(()=>({}))},
  async getPlaylists(){return req('/playlists')},
  async createPlaylist(name){return req('/playlists',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})})},
  async deletePlaylist(id){return req(`/playlists/${id}`,{method:'DELETE'})},
  async addToPlaylist(id,trackId){return req(`/playlists/${id}/tracks`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trackId})})},
  async removeFromPlaylist(id,trackId){return req(`/playlists/${id}/tracks/${trackId}`,{method:'DELETE'})},
  async getUsers(){return req('/admin/users')},
  async getArtists(){return req('/artists')},
  async uploadArtistImage(name,file){const f=new FormData();f.append('artistImage',file);const t=getToken();const r=await fetch(`${API}/artists/${encodeURIComponent(name)}/image`,{method:'PUT',headers:t?{Authorization:`Bearer ${t}`}:{},body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);return d},
  async deleteArtistImage(name){return req(`/artists/${encodeURIComponent(name)}/image`,{method:'DELETE'})},
  async updateArtist(name,data){return req(`/artists/${encodeURIComponent(name)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})},
  async ytInfo(url){return req('/yt/info',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})})},
  async ytImportCatalog(tracks){return req('/yt/import-catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tracks})})},
  async ytSearch(q){return req(`/yt/search?q=${encodeURIComponent(q)}`)},
  async ytSearchMusic(q,spotlightDuration=0){return req(`/yt/search-music?q=${encodeURIComponent(q)}&spotlightDuration=${spotlightDuration}`)},
  async ytStream(ytId){return req(`/yt/stream/${ytId}`)},
  async ytSave(data){return req('/yt/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})},
  async ytSaved(){return req('/yt/saved')},
  async ytRecommend(title,artist,ytId){return req(`/yt/recommend?title=${encodeURIComponent(title)}&artist=${encodeURIComponent(artist||'')}&ytId=${encodeURIComponent(ytId||'')}`)},
  async deleteYtTrack(id){return req(`/tracks/${id}/yt`,{method:'DELETE'})},
  async getCatalog(){return req('/catalog')},
  async addToCatalog(data){return req('/catalog',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})},
  async updateCatalog(id,data){return req(`/catalog/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})},
  async deleteCatalog(id){return req(`/catalog/${id}`,{method:'DELETE'})},
  async uploadCatalogCover(id,file){const f=new FormData();f.append('catalogCover',file);const t=getToken();const r=await fetch(`${API}/catalog/${id}/cover`,{method:'PUT',headers:t?{Authorization:`Bearer ${t}`}:{},body:f});const d=await r.json();if(!r.ok)throw new Error(d.error);return d},
  async reorderCatalog(orderedIds){return req('/catalog/reorder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderedIds})})},
  async searchCatalog(q){return req(`/catalog/search?q=${encodeURIComponent(q)}`)},
};
